-- 言いカエル おたすけAI
-- Supabase > SQL Editor で1回だけ実行してください。
-- 既存の diaries テーブル等には触れません。

create table if not exists public.iikaeru_rounds (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    played_date date not null,
    topic text not null,
    style text not null,
    ai_joined boolean not null default false,
    ai_answers jsonb,
    ai_revealed boolean not null default false,
    support_log jsonb not null default '[]'::jsonb,
    learned_words text[] not null default '{}'
);

revoke all on table public.iikaeru_rounds from anon, authenticated;
grant select, insert, update, delete on table public.iikaeru_rounds to service_role;

alter table public.iikaeru_rounds enable row level security;
